// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { loadEnvConfig } from "@next/env";
import { defineConfig } from "prisma/config";

// Load Next.js env files (.env.local etc.)
const projectDir = process.cwd();
loadEnvConfig(projectDir);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_URL is required for migrations with Supabase (bypasses PgBouncer)
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
