// tailwind.config.ts
const config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#006a71",
        "error-dim": "#d7383b",
        error: "#ff716c",
        background: "#0b0e14",
        "on-secondary": "#290067",
        "on-surface": "#ecedf6",
        "on-primary-fixed": "#003f43",
        outline: "#73757d",
        "tertiary-container": "#ff05e5",
        "surface-container-high": "#1c2028",
        "tertiary-dim": "#ff59e3",
        "on-tertiary-fixed-variant": "#6d0061",
        "on-tertiary": "#42003a",
        "on-tertiary-container": "#1b0017",
        "on-error-container": "#ffa8a3",
        "on-surface-variant": "#a9abb3",
        secondary: "#ac89ff",
        primary: "#8ff5ff",
        "on-background": "#ecedf6",
        "on-primary-fixed-variant": "#005e64",
        surface: "#0b0e14",
        "outline-variant": "#45484f",
        "on-error": "#490006",
        "surface-container-low": "#10131a",
        "on-secondary-fixed-variant": "#6300e2",
        "surface-container": "#161a21",
        "surface-container-highest": "#22262f",
        "primary-container": "#00eefc",
        "on-secondary-container": "#f8f1ff",
        "primary-fixed": "#00eefc",
        "surface-dim": "#0b0e14",
        "primary-dim": "#00deec",
        "on-tertiary-fixed": "#33002d",
        "secondary-fixed-dim": "#ceb9ff",
        "tertiary-fixed": "#ff85e4",
        "surface-container-lowest": "#000000",
        "inverse-surface": "#f9f9ff",
        "inverse-on-surface": "#52555c",
        "surface-tint": "#8ff5ff",
        "secondary-container": "#7000ff",
        tertiary: "#ff59e3",
        "secondary-fixed": "#dac9ff",
        "tertiary-fixed-dim": "#ff68e3",
        "secondary-dim": "#874cff",
        "error-container": "#9f0519",
        "surface-bright": "#282c36",
        "on-primary": "#005d63",
        "on-secondary-fixed": "#41009a",
        "primary-fixed-dim": "#00deec",
        "surface-variant": "#22262f",
        "on-primary-container": "#005359",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-headline)"],
        body: ["var(--font-body)"],
        label: ["var(--font-body)"],
      },
    },
  },
  plugins: [],
};

export default config;